---
default_preset: academic
presets:
  academic:
    kanbun:
      kaeriten:
        size: 9pt
        shift:
          up: 2pt
          right: 3pt
          down: 0pt
          left: 0pt
      side:
        min_width: 0.55zw
