---
default_preset: academic
presets:
  academic:
    kanbun:
      kaeriten:
        size: 9pt
        shift:
          up: 0pt
          right: 0pt
          down: 1.5pt
          left: 2pt
      side:
        min_width: 0.55zw
