---
default_preset: academic
presets:
  academic:
    kanbun:
      furigana:
        shift:
          up: 0pt
          right: 3pt
          down: 0pt
          left: 0pt
      kaeriten:
        shift:
          up: 0pt
          right: 3pt
          down: 0.5pt
          left: 0pt
      okurigana:
        shift:
          up: 0pt
          right: 3pt
          down: 1pt
          left: 0pt
      side:
        min_width: 0.6zw
