---
default_preset: academic
presets:
  academic:
    kanbun:
      okurigana:
        size: 10pt
        shift:
          up: 0pt
          right: 3pt
          down: 2pt
          left: 0pt
      side:
        min_width: 0.55zw
